# Generated by Django 4.2.2 on 2023-06-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparePartsStore', '0002_remove_item_category_item_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categories',
            new_name='category',
        ),
    ]
