# Generated by Django 4.2.2 on 2023-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparePartsStore', '0004_alter_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
